project_id = "qprtljmxfulproevgydc"

[functions.bootstrap-superadmin]
verify_jwt = false

[functions.assign-creator-role]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = false

[functions.lipana-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = false

[functions.initiate-paystack]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.verify-paystack]
verify_jwt = false

